/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Note filter
 */
export interface NoteFilterDto {

  /**
   * Set of identifiers of entities
   */
  ids?: Array<string>;

  /**
   * Note title
   */
  title?: string;
}
