/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NoteDtoDto {

  /**
   * Content
   */
  content?: string;

  /**
   * Item ID
   */
  id?: string;

  /**
   * Title
   */
  title?: string;
}
