/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NoteDtoDto } from '../models/note-dto-dto';
import { PageMetadataDto } from '../models/page-metadata-dto';
export interface PagedModelNoteDtoDto {
  content?: Array<NoteDtoDto>;
  page?: PageMetadataDto;
}
