/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NoteDtoDto } from '../../models/note-dto-dto';
import { NoteSaveDtoDto } from '../../models/note-save-dto-dto';

export interface UpdateNote$Params {
  id: string;
      body: NoteSaveDtoDto
}

export function updateNote(http: HttpClient, rootUrl: string, params: UpdateNote$Params, context?: HttpContext): Observable<StrictHttpResponse<NoteDtoDto>> {
  const rb = new RequestBuilder(rootUrl, updateNote.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NoteDtoDto>;
    })
  );
}

updateNote.PATH = '/api/v1/note/{id}';
